version: "3"

services:

    sql-server:
        image: mcr.microsoft.com/mssql/server
        container_name: sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"  
        ports:
            - "1433:1433"

    api-desafio-conta:
        container_name: desafio-conta-api
        build: 
            context: ../src
            dockerfile: ./services/DesafioConta.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5011;http://+5012 
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - sql-server    
        ports:
            - "5011:5011"

    web-mvc:
        container_name: web-mvc
        build:
            context: ../src
            dockerfile: ./web/DesafioConta.WebApp.MVC/Dockerfile
        restart: always            
        environment:    
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001   
        volumes: 
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - api-desafio-conta
        ports:
            - "5001:5001"
            
    desafio-conta-proxy:
        container_name: desafio-conta-proxy    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys:    
         