// <auto-generated />
using System;
using DesafioConta.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioConta.Infra.Migrations
{
    [DbContext(typeof(CheckingAccountsContext))]
    [Migration("20201115004130_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DesafioConta.Domain.Accounts.CheckingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agency")
                        .HasColumnType("int")
                        .HasColumnName("Agency");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMonetization")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("CheckingAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2414f7af-a310-479a-b82f-3d3c1e4741d4"),
                            Agency = 1,
                            Balance = 0m,
                            CreationDate = new DateTime(2020, 10, 30, 21, 41, 29, 846, DateTimeKind.Local).AddTicks(9819),
                            LastMonetization = new DateTime(2020, 10, 30, 21, 41, 29, 848, DateTimeKind.Local).AddTicks(238),
                            Number = 1
                        });
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CheckingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckingAccountId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b17554a5-1434-49df-8e8a-157b8ee96a5b"),
                            CheckingAccountId = new Guid("2414f7af-a310-479a-b82f-3d3c1e4741d4"),
                            CreationDate = new DateTime(2020, 11, 14, 21, 41, 29, 849, DateTimeKind.Local).AddTicks(7406)
                        });
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.CheckingAccount", b =>
                {
                    b.OwnsMany("DesafioConta.Domain.Accounts.OperationsHistory", "OperationsHistory", b1 =>
                        {
                            b1.Property<Guid>("CheckingAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Operation")
                                .HasColumnType("int");

                            b1.HasKey("CheckingAccountId", "Id");

                            b1.ToTable("OperationsHistory");

                            b1.WithOwner("CheckingAccount")
                                .HasForeignKey("CheckingAccountId");

                            b1.Navigation("CheckingAccount");
                        });

                    b.Navigation("OperationsHistory");
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.Customer", b =>
                {
                    b.HasOne("DesafioConta.Domain.Accounts.CheckingAccount", "CheckingAccount")
                        .WithOne("Customer")
                        .HasForeignKey("DesafioConta.Domain.Accounts.Customer", "CheckingAccountId")
                        .IsRequired();

                    b.OwnsOne("DesafioConta.Domain.Accounts.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bairro")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Complemento")
                                .HasColumnType("varchar(250)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Estado")
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Estado");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Numero")
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Numero");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("b17554a5-1434-49df-8e8a-157b8ee96a5b"),
                                    Bairro = "Money",
                                    Cep = "94064340",
                                    Cidade = "Porto Alegre",
                                    Complemento = "Casa",
                                    Estado = "RS",
                                    Logradouro = "Warren Street",
                                    Numero = "123"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("b17554a5-1434-49df-8e8a-157b8ee96a5b"),
                                    Number = "34074230046"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("b17554a5-1434-49df-8e8a-157b8ee96a5b"),
                                    Address = "warren@buffet.com"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("b17554a5-1434-49df-8e8a-157b8ee96a5b"),
                                    FirstName = "Warren",
                                    LastName = "Buffet"
                                });
                        });

                    b.Navigation("Address");

                    b.Navigation("CheckingAccount");

                    b.Navigation("Cpf");

                    b.Navigation("Email");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.CheckingAccount", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
