// <auto-generated />
using System;
using DesafioConta.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioConta.Infra.Migrations
{
    [DbContext(typeof(CheckingAccountsContext))]
    [Migration("20201114021921_AddEmailSeed")]
    partial class AddEmailSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DesafioConta.Domain.Accounts.CheckingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agency")
                        .HasColumnType("int")
                        .HasColumnName("Agency");

                    b.Property<decimal>("Balance")
                        .HasColumnType("Money");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMonetization")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("CheckingAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29ebab6a-7857-4a55-967f-66651c269f86"),
                            Agency = 1,
                            Balance = 0m,
                            CreationDate = new DateTime(2020, 11, 13, 23, 19, 20, 911, DateTimeKind.Local).AddTicks(8805),
                            LastMonetization = new DateTime(2020, 11, 13, 23, 19, 20, 913, DateTimeKind.Local).AddTicks(1834),
                            Number = 100
                        });
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CheckingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckingAccountId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3b9066e-c0d1-49fc-aafb-31bbb65aab12"),
                            CheckingAccountId = new Guid("29ebab6a-7857-4a55-967f-66651c269f86"),
                            CreationDate = new DateTime(2020, 11, 13, 23, 19, 20, 915, DateTimeKind.Local).AddTicks(4180)
                        });
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.OperationsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("Money");

                    b.Property<Guid>("CheckingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckingAccountId");

                    b.ToTable("OperationsHistory");
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.Customer", b =>
                {
                    b.HasOne("DesafioConta.Domain.Accounts.CheckingAccount", "CheckingAccount")
                        .WithOne("Customer")
                        .HasForeignKey("DesafioConta.Domain.Accounts.Customer", "CheckingAccountId")
                        .IsRequired();

                    b.OwnsOne("DesafioConta.Domain.Accounts.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bairro")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Complemento")
                                .HasColumnType("varchar(250)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Estado")
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Estado");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Numero")
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Numero");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("d3b9066e-c0d1-49fc-aafb-31bbb65aab12"),
                                    Bairro = "Money",
                                    Cep = "94064340",
                                    Cidade = "Porto Alegre",
                                    Complemento = "Casa",
                                    Estado = "RS",
                                    Logradouro = "Warren Street",
                                    Numero = "123"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("d3b9066e-c0d1-49fc-aafb-31bbb65aab12"),
                                    Number = "34074230046"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("d3b9066e-c0d1-49fc-aafb-31bbb65aab12"),
                                    Address = "warren@buffet.com"
                                });
                        });

                    b.OwnsOne("DesafioConta.Domain.Accounts.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("d3b9066e-c0d1-49fc-aafb-31bbb65aab12"),
                                    FirstName = "Warren",
                                    LastName = "Buffet"
                                });
                        });

                    b.Navigation("Address");

                    b.Navigation("CheckingAccount");

                    b.Navigation("Cpf");

                    b.Navigation("Email");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.OperationsHistory", b =>
                {
                    b.HasOne("DesafioConta.Domain.Accounts.CheckingAccount", "CheckingAccount")
                        .WithMany("OperationsHistory")
                        .HasForeignKey("CheckingAccountId")
                        .IsRequired();

                    b.Navigation("CheckingAccount");
                });

            modelBuilder.Entity("DesafioConta.Domain.Accounts.CheckingAccount", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("OperationsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
